### ISSUE TITLE
rename `count` to `tokens2counts` ? 

### ISSUE THREAD

**Issue by vlandham** [learntextvis/textkit#21]
If we think of the addition of counts as a transformation of "tokens" to "tokens + counts" it could make sense to have this function be named `tokens2counts`. 

This would better specify to the end user what the input of this function are, and would keep naming more consistent. 

Likewise, the similar POS tagging feature could be named `tokens2pos` or more confusingly  but more accurately `tokens2poss` (i would vote the former). This would be a transformation of "tokens" to "tokens + pos tags".

Thoughts?

**Comment by arnicas** [comment]
+1. Good idea.  (Also, tokens2pos not poss :)

**Comment by iros** [comment]
Will rename in my PR!

**Comment by vlandham** [comment]
woops. i think i stepped on toes - i already did a push to do this change.

Sorry!
