### ISSUE TITLE
nonewlines should support non-unix line breaks

### ISSUE THREAD

**Issue by vlandham** [learntextvis/textkit#40]
windows `CRLF` and just the `CR` should also be supported. Right now only `LF` is supported.

**Comment by Fil** [comment]
for some reason it seems that `tokens2pos` and `tokens2counts` output `CRLF`, but `text2words` outputs `LF`.

One uses `output()` which calls `click.echo()`, the other uses `csv.writer()`

**Comment by vlandham** [comment]
closed by @Fil !
