### ISSUE TITLE
rename transformation commands to keep them consistent.

### ISSUE THREAD

**Issue by vlandham** [learntextvis/textkit#42]
I should have made this a PR - but wasn't thinking, so I can revert if needed. 
The latest `0.2.0` release renames some of the transformation functions, to keep more in line with our `tokens2counts` and `tokens2pos` commands. 

Specifically:

* `lowercase` has become `tokens2lower`
* `uppercase` has become `tokens2upper`
* `stem` has become `tokens2stem`
* `topbigrams` has become `tokens2topbigrams`

This keeps them all contained together in the `--help` documentation, and makes it more clear what content they are expecting. The tradeoff is they are slightly more verbose.

Thoughts @iros / @arnicas ?

changed in 2685e9425e092ccb7fb39e428d0304249b33e144

**Comment by iros** [comment]
Sorry +1
